name: Build

on:
  workflow_dispatch:
    branches: [ '*' ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ '*' ]
    paths-ignore: [ '**.md' ]

jobs:
  test:
    -runs:
      using: 'docker'
      image: 'Dockerfile'
    # runs-on: ubuntu-latest
    #
    # strategy:
    #   matrix:
    #     ruby-version: [ '2.7.0' ]
    #
    # steps:
    # - uses: actions/checkout@v2
    # - name: Set up Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: ${{ matrix.ruby-version }}
    #
    # - uses: actions/cache@v1
    #   with:
    #     path: vendor/bundle
    #     key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
    #
    # # - run: gem update --system 3.4.22
    # - run: sudo apt-get install -y --no-install-recommends build-essential
    # - run: gem install bundler -v 2.4.22
    #
    # - run: bundle config set deployment 'true'
    # - run: bundle config build.nokogiri --use-system-libraries
    # - run: bundle install
    #
    # - run: bundle exec middleman build
