name: Build

on:
  push:
    branches: [ '*' ]
    paths-ignore: [ 'README.md', '**.html.md', '**.md.erb' ]
  pull_request:
    branches: [ '*' ]
    paths-ignore: [ 'README.md', '**.html.md', '**.md.erb' ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [ '2.7.0' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: gems-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}

    # - run: gem update --system 3.4.22
    - run: sudo apt-get install -y --no-install-recommends build-essential nodejs
    - run: gem install bundler -v 2.4.22

    - run: bundle config set deployment 'true'
    - run: bundle config build.nokogiri --use-system-libraries
    - run: bundle install

    - run: bundle exec middleman build
